"""
FastAPI serving application for GPON Router Predictive Maintenance.

Endpoints
---------
POST /predict
    Accepts telemetry JSON, returns a failure probability for the next 7 days.
    If probability > 0.7 a diagnostic ticket is generated by the local Ollama LLM.

GET /health
    Liveness probe.
"""

import json
import logging
import os

import httpx
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="GPON Predictive Maintenance API",
    description="Predicts GPON router hardware failures 7 days in advance.",
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# Configuration (override via environment variables)
# ---------------------------------------------------------------------------

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "mistral")
FAILURE_THRESHOLD = float(os.getenv("FAILURE_THRESHOLD", "0.7"))

# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

_model = None


def _load_model():
    """Lazy-load the XGBoost model from disk or return a mock for local dev."""
    global _model
    if _model is not None:
        return _model

    model_path = os.getenv("MODEL_PATH", "model.xgb")
    if os.path.exists(model_path):
        from xgboost import XGBClassifier

        _model = XGBClassifier()
        _model.load_model(model_path)
        logger.info("Loaded XGBoost model from %s", model_path)
    else:
        logger.warning("Model file not found at %s — using mock predictor", model_path)
        _model = _MockModel()

    return _model


class _MockModel:
    """Deterministic mock model used when no trained model is available."""

    def predict_proba(self, X):  # noqa: N803
        # Simple heuristic: high risk when RX power is very low or temp is very high
        rx = X[:, 0]
        temp = X[:, 1]
        prob = np.clip(((-rx - 5) / 25 + (temp - 30) / 50) / 2, 0.0, 1.0)
        return np.column_stack([1 - prob, prob])


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------


class TelemetryInput(BaseModel):
    rx_power_dbm: float = Field(..., description="Received optical power in dBm (typical: -30 to -5)", example=-15.0)
    temperature_c: float = Field(..., description="Device temperature in Celsius", example=55.0)
    latency_ms: float = Field(..., description="Round-trip latency in milliseconds", example=12.5)
    tx_power_dbm: float = Field(..., description="Transmitted optical power in dBm (typical: -5 to 3)", example=1.0)
    ber: float = Field(..., description="Bit Error Rate (0 to ~1e-3)", example=0.0001)
    uptime_hours: float = Field(..., description="Device uptime in hours", example=2400.0)


class PredictionOutput(BaseModel):
    failure_probability: float
    failure_predicted: bool
    diagnostic_report: str | None = None


# ---------------------------------------------------------------------------
# Ollama integration
# ---------------------------------------------------------------------------


async def _call_ollama(telemetry: TelemetryInput, probability: float) -> str:
    """Request a plain-text diagnostic report from the local Ollama LLM."""
    prompt = (
        f"You are a network reliability engineer. A GPON router is showing signs of "
        f"potential hardware failure within the next 7 days.\n\n"
        f"Telemetry snapshot:\n"
        f"  RX Power      : {telemetry.rx_power_dbm} dBm\n"
        f"  Temperature   : {telemetry.temperature_c} °C\n"
        f"  Latency       : {telemetry.latency_ms} ms\n"
        f"  TX Power      : {telemetry.tx_power_dbm} dBm\n"
        f"  BER           : {telemetry.ber}\n"
        f"  Uptime        : {telemetry.uptime_hours} hours\n"
        f"  Failure prob. : {probability:.2%}\n\n"
        f"Generate a concise diagnostic ticket (max 150 words) that includes:\n"
        f"1. Most likely root cause\n"
        f"2. Recommended immediate action\n"
        f"3. Suggested preventive maintenance steps"
    )

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(f"{OLLAMA_BASE_URL}/api/generate", json=payload)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "").strip()


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.get("/health", tags=["ops"])
async def health():
    return {"status": "ok"}


@app.post("/predict", response_model=PredictionOutput, tags=["prediction"])
async def predict(telemetry: TelemetryInput):
    """
    Run the XGBoost failure-prediction model on the supplied telemetry.

    If the failure probability exceeds the configured threshold (default 0.7),
    a diagnostic report is generated by the Ollama LLM running locally.
    """
    model = _load_model()

    features = np.array(
        [[
            telemetry.rx_power_dbm,
            telemetry.temperature_c,
            telemetry.latency_ms,
            telemetry.tx_power_dbm,
            telemetry.ber,
            telemetry.uptime_hours,
        ]]
    )

    try:
        proba = float(model.predict_proba(features)[0][1])
    except Exception as exc:
        logger.exception("Prediction failed")
        raise HTTPException(status_code=500, detail=f"Prediction error: {exc}") from exc

    failure_predicted = proba > FAILURE_THRESHOLD
    diagnostic = None

    if failure_predicted:
        logger.info("High failure probability (%.2f) — querying Ollama for diagnostic report", proba)
        try:
            diagnostic = await _call_ollama(telemetry, proba)
        except httpx.HTTPError as exc:
            logger.warning("Ollama request failed: %s — continuing without report", exc)
            diagnostic = (
                f"[Ollama unavailable] High failure probability ({proba:.2%}) detected. "
                "Please inspect device manually."
            )

    return PredictionOutput(
        failure_probability=round(proba, 4),
        failure_predicted=failure_predicted,
        diagnostic_report=diagnostic,
    )
